import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen text-gray-900`}>
        <nav className="sticky top-0 z-10 bg-white/80 backdrop-blur border-b">
          <div className="max-w-6xl mx-auto px-4 py-3 flex items-center justify-between">
            <a href="/" className="font-semibold">{process.env.NEXT_PUBLIC_APP_NAME || 'Certificates'}</a>
            <div className="flex items-center gap-4 text-sm">
              <a href="/verify" className="hover:underline">Verify</a>
              <a href="/login" className="hover:underline">Login</a>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
